### ISSUE TITLE
Add support for `Authorization` header in `quetz-client`

### ISSUE THREAD

**Issue by najose** [wolfv/quetz-docker#7]
See https://github.com/mamba-org/quetz-client/issues/44.

**Comment by wolfv** [comment]
I have opened this PR https://github.com/mamba-org/quetz-client/pull/45

Do you think you can test it?

**Comment by najose** [comment]
@wolfv, Sure I'll test it and update in the PR.

**Comment by najose** [comment]
This is working as expected, so closing this issue. Thanks!
